#!/usr/bin/env bash
set -euo pipefail

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${CYAN}[prism]${NC} $*"; }
ok()    { echo -e "${GREEN}[ok]${NC} $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC} $*"; }
err()   { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

check_deps() {
  for cmd in docker git; do
    if ! command -v "$cmd" &>/dev/null; then
      err "$cmd is required but not installed."
    fi
  done
  if ! docker compose version &>/dev/null && ! docker-compose version &>/dev/null; then
    err "docker compose (v2) or docker-compose (v1) is required."
  fi
  ok "All dependencies found."
}

prompt_val() {
  local varname="$1" prompt_text="$2" default="${3:-}" required="${4:-false}"
  local display_default=""
  if [ -n "$default" ]; then display_default=" [$default]"; fi
  read -rp "$(echo -e "${CYAN}${prompt_text}${display_default}: ${NC}")" input
  val="${input:-$default}"
  if [ "$required" = "true" ] && [ -z "$val" ]; then
    err "Value is required for $varname"
  fi
  eval "$varname=\"\$val\""
}

setup_env() {
  if [ -f .env ]; then
    warn ".env already exists. Backing up to .env.bak"
    cp .env .env.bak
  fi

  info "Configuring Prism self-hosted deployment..."
  echo ""

  prompt_val DOMAIN "Domain (for Traefik routes)" "localhost"
  prompt_val SITE_URL "Site URL" "http://localhost:3000"
  prompt_val ACME_EMAIL "Email for Let's Encrypt" "" "false"
  prompt_val POSTGRES_PASSWORD "PostgreSQL password" "postgres"
  prompt_val JWT_SECRET "JWT secret (32+ chars)" "$(openssl rand -hex 24 2>/dev/null || echo 'change-me-to-a-long-secret')"

  echo ""
  info "LLM Provider (leave blank to skip)"
  info "  cloud:  openai, anthropic, google, deepseek, grok, openrouter"
  info "  new:    nvidia-nim, groq, cerebras, cloudflare-workers, fireworks, zai"
  info "  local:  ollama, koboldcpp, llamacpp, sglang"
  echo ""

  prompt_val LLM_PROVIDER "Default LLM provider" "openai"
  prompt_val LLM_MODEL "Default LLM model" "gpt-3.5-turbo"

  echo ""
  info "API Keys (leave blank to skip, you can edit .env later)"
  echo ""

  prompt_val OPENAI_API_KEY "OpenAI API key" ""
  prompt_val ANTHROPIC_API_KEY "Anthropic API key" ""
  prompt_val GOOGLE_API_KEY "Google Gemini API key" ""
  prompt_val DEEPSEEK_API_KEY "DeepSeek API key" ""
  prompt_val GROQ_API_KEY "Groq API key" ""
  prompt_val NVIDIA_NIM_API_KEY "NVIDIA NIM API key" ""
  prompt_val CEREBRAS_API_KEY "Cerebras API key" ""
  prompt_val FIREWORKS_API_KEY "Fireworks API key" ""
  prompt_val CLOUDFLARE_WORKERS_API_KEY "Cloudflare Workers API key" ""
  prompt_val ZAI_API_KEY "Z.AI API key" ""

  echo ""
  prompt_val ENABLE_OLLAMA "Enable Ollama container? (y/n)" "n"

  cat > .env << ENVEOF
# Prism Self-Hosting - Auto-generated by setup.sh
DOMAIN=${DOMAIN}
SITE_URL=${SITE_URL}
ACME_EMAIL=${ACME_EMAIL}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
LLM_PROVIDER=${LLM_PROVIDER}
LLM_MODEL=${LLM_MODEL}
OPENAI_API_KEY=${OPENAI_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
GOOGLE_API_KEY=${GOOGLE_API_KEY}
DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
GROQ_API_KEY=${GROQ_API_KEY}
NVIDIA_NIM_API_KEY=${NVIDIA_NIM_API_KEY}
CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
CLOUDFLARE_WORKERS_API_KEY=${CLOUDFLARE_WORKERS_API_KEY}
ZAI_API_KEY=${ZAI_API_KEY}
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:3002
STORAGE_PROVIDER=supabase
STORAGE_BUCKET=prism-chat-history
RATE_LIMIT_REQUESTS=100
RATE_LIMIT_WINDOW_MS=900000
LOG_LEVEL=info
ENABLE_TELEMETRY=false
ENVEOF

  ok ".env written."
}

pull_ollama_model() {
  if [ "${ENABLE_OLLAMA:-n}" = "y" ]; then
    local default_model="llama3.2"
    prompt_val OLLAMA_MODEL "Ollama model to pull" "$default_model"
    info "Pulling ${OLLAMA_MODEL} (this may take a while)..."
    docker exec prism-ollama-1 ollama pull "$OLLAMA_MODEL" 2>/dev/null || \
      docker exec ollama ollama pull "$OLLAMA_MODEL" 2>/dev/null || \
      warn "Could not pull model. Start Ollama first, then run: docker exec ollama ollama pull $OLLAMA_MODEL"
  fi
}

deploy() {
  local compose_cmd
  if docker compose version &>/dev/null; then
    compose_cmd="docker compose"
  else
    compose_cmd="docker-compose"
  fi

  local ollama_profile=""
  if [ "${ENABLE_OLLAMA:-n}" = "y" ]; then
    ollama_profile="--profile ollama"
  fi

  info "Building and starting services..."
  $compose_cmd up -d --build $ollama_profile

  ok "Services started."
  echo ""
  info "Prism is running:"
  info "  Web:      http://localhost:3001"
  info "  API:      http://localhost:3000"
  info "  Hono API: http://localhost:3002"
  if [ "${ENABLE_OLLAMA:-n}" = "y" ]; then
    info "  Ollama:   http://localhost:11434"
  fi
  info "  Traefik:  http://localhost:8080"
  echo ""
  info "To view logs:     $compose_cmd logs -f"
  info "To stop:          $compose_cmd down"
  info "To reconfigure:   ./setup.sh --env-only"
}

main() {
  local env_only="${1:-}"

  echo ""
  echo -e "${CYAN}========================================${NC}"
  echo -e "${CYAN}  Prism Self-Hosting Setup${NC}"
  echo -e "${CYAN}========================================${NC}"
  echo ""

  check_deps

  if [ ! -d ".git" ]; then
    warn "Not running from repo root. Cloning..."
    git clone https://github.com/anomalyco/Prism.git /tmp/prism-setup
    cd /tmp/prism-setup
  fi

  setup_env

  if [ "$env_only" = "--env-only" ]; then
    ok "Environment configured. Run './setup.sh' to deploy."
    exit 0
  fi

  deploy
  pull_ollama_model
}

main "$@"
