// Define action types for the Redux store
export const CHAT_ACTIONS = {
  ADD_MESSAGE: 'chat/ADD_MESSAGE',
  SET_MESSAGES: 'chat/SET_MESSAGES',
  UPDATE_MESSAGE: 'chat/UPDATE_MESSAGE',
  DELETE_MESSAGE: 'chat/DELETE_MESSAGE',
  SET_CURRENT_SESSION: 'chat/SET_CURRENT_SESSION',
  SET_SESSIONS: 'chat/SET_SESSIONS',
  ADD_SESSION: 'chat/ADD_SESSION',
  DELETE_SESSION: 'chat/DELETE_SESSION',
  SET_LOADING: 'chat/SET_LOADING',
  SET_CONTEXT: 'chat/SET_CONTEXT',
  CLEAR_HISTORY: 'chat/CLEAR_HISTORY',
} as const;

export const AI_CONFIG_ACTIONS = {
  SET_AI_CONFIG: 'aiConfig/SET_AI_CONFIG',
  UPDATE_AI_CONFIG: 'aiConfig/UPDATE_AI_CONFIG',
  SET_AVAILABLE_MODELS: 'aiConfig/SET_AVAILABLE_MODELS',
  SET_FETCHING_MODELS: 'aiConfig/SET_FETCHING_MODELS',
} as const;

export const UI_ACTIONS = {
  SET_DISPLAY_MODE: 'ui/SET_DISPLAY_MODE',
  SET_FONT_SIZE: 'ui/SET_FONT_SIZE',
  SET_CHAT_OPEN: 'ui/SET_CHAT_OPEN',
  SET_SHOW_PROMPTS: 'ui/SET_SHOW_PROMPTS',
  SET_SHOW_MENU: 'ui/SET_SHOW_MENU',
  INCREASE_FONT_SIZE: 'ui/INCREASE_FONT_SIZE',
  DECREASE_FONT_SIZE: 'ui/DECREASE_FONT_SIZE',
} as const;

export const SETTINGS_ACTIONS = {
  SET_DISPLAY_SETTINGS: 'settings/SET_DISPLAY_SETTINGS',
  SET_SYSTEM_PROMPT: 'settings/SET_SYSTEM_PROMPT',
} as const;

export const PROMPTS_ACTIONS = {
  SET_PROMPT_SHORTCUTS: 'prompts/SET_PROMPT_SHORTCUTS',
  ADD_PROMPT_SHORTCUT: 'prompts/ADD_PROMPT_SHORTCUT',
  UPDATE_PROMPT_SHORTCUT: 'prompts/UPDATE_PROMPT_SHORTCUT',
  DELETE_PROMPT_SHORTCUT: 'prompts/DELETE_PROMPT_SHORTCUT',
  SET_LOADING: 'prompts/SET_LOADING',
} as const;

export const NETWORK_ACTIONS = {
  SET_ONLINE_STATUS: 'network/SET_ONLINE_STATUS',
  SET_LAST_SYNC: 'network/SET_LAST_SYNC',
} as const;